export type TagKey = keyof typeof BOOK_TAGS

export const BOOK_TAGS = {
  sci_fi: { ru: 'научная фантастика', en: 'sci-fi', zh: '科幻' },
  fantasy: { ru: 'фэнтези', en: 'fantasy', zh: '奇幻' },
  adventure: { ru: 'приключения', en: 'adventure', zh: '冒险' },
  shounen: { ru: 'сёнэн', en: 'shounen', zh: '少年' },
  shoujo: { ru: 'сёдзё', en: 'shoujo', zh: '少女' },
  seinen: { ru: 'сэйнэн', en: 'seinen', zh: '青年' },
  josei: { ru: 'дзёсэй', en: 'josei', zh: '女性' },
  romance: { ru: 'романтика', en: 'romance', zh: '爱情' },
  comedy: { ru: 'комедия', en: 'comedy', zh: '喜剧' },
  drama: { ru: 'драма', en: 'drama', zh: '剧情' },
  slice_of_life: { ru: 'повседневность', en: 'slice of life', zh: '日常' },
  action: { ru: 'экшен', en: 'action', zh: '动作' },
  thriller: { ru: 'триллер', en: 'thriller', zh: '惊悚' },
  mystery: { ru: 'детектив', en: 'mystery', zh: '悬疑' },
  horror: { ru: 'ужасы', en: 'horror', zh: '恐怖' },
  post_apocalyptic: { ru: 'постапокалипсис', en: 'post-apocalyptic', zh: '末日' },
  cyberpunk: { ru: 'киберпанк', en: 'cyberpunk', zh: '赛博朋克' },
  historical: { ru: 'исторический', en: 'historical', zh: '历史' },
  martial_arts: { ru: 'боевые искусства', en: 'martial arts', zh: '武术' },
  psychological: { ru: 'психология', en: 'psychological', zh: '心理' },
  supernatural: { ru: 'сверхъестественное', en: 'supernatural', zh: '超自然' },
  magic: { ru: 'магия', en: 'magic', zh: '魔法' },
  school: { ru: 'школа', en: 'school', zh: '校园' },
  mecha: { ru: 'меха', en: 'mecha', zh: '机甲' },
  isekai: { ru: 'исекай (попаданцы)', en: 'isekai', zh: '异世界' },
  game: { ru: 'игра', en: 'game', zh: '游戏' },
  dystopia: { ru: 'антиутопия', en: 'dystopia', zh: '反乌托邦' },
  music: { ru: 'музыка', en: 'music', zh: '音乐' },
  sports: { ru: 'спорт', en: 'sports', zh: '体育' },
  tragedy: { ru: 'трагедия', en: 'tragedy', zh: '悲剧' },
  space: { ru: 'космос', en: 'space', zh: '太空' },
  vampire: { ru: 'вампиры', en: 'vampire', zh: '吸血鬼' },
  zombie: { ru: 'зомби', en: 'zombie', zh: '丧尸' },
  military: { ru: 'военный', en: 'military', zh: '军事' },
  wuxia: { ru: 'уся', en: 'wuxia', zh: '武侠' },
  xianxia: { ru: 'сянься', en: 'xianxia', zh: '仙侠' },
}

export const ALLOWED_TAG_KEYS = Object.keys(BOOK_TAGS)
