FROM python:3.11-slim

WORKDIR /app

COPY apps/server/hanlp_server.py .

RUN pip install --no-cache-dir \
    "transformers<4.30.0" \
    "tokenizers<0.14.0" \
    hanlp \
    fastapi uvicorn flask

EXPOSE 8765

CMD ["python", "hanlp_server.py"]
