# =================================================================
# Этап 1: "builder" - Установка зависимостей и сборка клиента
# =================================================================
FROM oven/bun:1.3-slim AS builder

WORKDIR /usr/src/app

COPY package.json bun.lock ./
COPY apps/client/package.json ./apps/client/
COPY packages/plugin-api/package.json ./packages/plugin-api/
COPY packages/plugin-grammar-rules/package.json ./packages/plugin-grammar-rules/

RUN bun install --ignore-scripts

# Copy all source files
COPY . .

ARG VITE_UMAMI_WEBSITE_ID
ARG VITE_UMAMI_URL

ENV VITE_UMAMI_WEBSITE_ID=$VITE_UMAMI_WEBSITE_ID
ENV VITE_UMAMI_URL=$VITE_UMAMI_URL

ARG V_CLIENT="dev"
ARG VITE_API_URL

ENV VITE_APP_VERSION=$V_CLIENT
ENV VITE_API_URL=$VITE_API_URL

RUN bun --cwd=apps/client run build
RUN bun --cwd=apps/client run story:build

# =================================================================
# Этап 2: "release" - Создание финального образа с Nginx
# =================================================================
FROM nginx:stable-alpine

COPY --from=builder /usr/src/app/apps/client/dist /usr/share/nginx/html
COPY --from=builder /usr/src/app/apps/client/storybook-static /usr/share/nginx/html/docs
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3334

CMD ["nginx", "-g", "daemon off;"]
