export const ERROR_CODES = {
  AUTH: {
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    NO_CODE_PROVIDED: 'NO_CODE_PROVIDED',
    NO_SESSION_ID: 'NO_SESSION_ID',
    INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
    VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
    INVALID_USERNAME: 'INVALID_USERNAME',
    USERNAME_TAKEN: 'USERNAME_TAKEN',
    OAUTH_TOKEN_EXCHANGE_FAILED: 'OAUTH_TOKEN_EXCHANGE_FAILED',
    OAUTH_USER_INFO_FAILED: 'OAUTH_USER_INFO_FAILED',
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    CANNOT_DEMOTE_LAST_ADMIN: 'CANNOT_DEMOTE_LAST_ADMIN',
    CANNOT_DELETE_SELF: 'CANNOT_DELETE_SELF',
    CANNOT_DELETE_LAST_ADMIN: 'CANNOT_DELETE_LAST_ADMIN',
  },
  BOOK: {
    NOT_FOUND: 'BOOK_NOT_FOUND',
    PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
    MANGA_NOT_FOUND: 'MANGA_NOT_FOUND',
    MANGA_NO_IMAGES: 'MANGA_NO_IMAGES',
    CANNOT_EDIT_PUBLIC: 'CANNOT_EDIT_PUBLIC_BOOK',
    CANNOT_DELETE_PUBLIC: 'CANNOT_DELETE_PUBLIC_BOOK',
    FILE_REQUIRED: 'FILE_REQUIRED',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    ACCESS_DENIED: 'BOOK_ACCESS_DENIED',
    NO_PAGES_TO_ANALYZE: 'NO_PAGES_TO_ANALYZE',
  },
  DICTIONARY: {
    WORD_NOT_FOUND: 'WORD_NOT_FOUND',
    AUDIO_AND_WORD_REQUIRED: 'AUDIO_AND_WORD_REQUIRED',
    DECK_NOT_FOUND: 'DECK_NOT_FOUND',
    PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND',
  },
  HIGHLIGHT: {
    NOT_FOUND: 'HIGHLIGHT_NOT_FOUND',
  },
  PLUGIN: {
    NOT_FOUND: 'PLUGIN_NOT_FOUND',
    ALREADY_INSTALLED: 'PLUGIN_ALREADY_INSTALLED',
    INVALID_MANIFEST: 'INVALID_PLUGIN_MANIFEST',
  },
  LIMITS: {
    EXCEEDED: 'LIMIT_EXCEEDED',
    BOOK_LIMIT_EXCEEDED: 'BOOK_LIMIT_EXCEEDED',
    TOKEN_LIMIT_EXCEEDED: 'TOKEN_LIMIT_EXCEEDED',
  },
  QUIZ: {
    LEVEL_LOCKED: 'QUIZ_LEVEL_LOCKED',
    GENERATION_FAILED: 'QUIZ_GENERATION_FAILED',
  },
  TTS: {
    TEXT_REQUIRED: 'TTS_TEXT_REQUIRED',
    TEXT_TOO_LONG: 'TTS_TEXT_TOO_LONG',
    NOT_CONFIGURED: 'TTS_NOT_CONFIGURED',
    GENERATION_FAILED: 'TTS_GENERATION_FAILED',
  },
  OCR: {
    NOT_CONFIGURED: 'OCR_NOT_CONFIGURED',
    PROCESSING_FAILED: 'OCR_PROCESSING_FAILED',
  },
  SYSTEM: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
    ADMIN_ONLY: 'ADMIN_ONLY',
    NO_DATA_TO_UPDATE: 'NO_DATA_TO_UPDATE',
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
    LLM_NOT_CONFIGURED: 'LLM_NOT_CONFIGURED',
    LLM_ERROR: 'LLM_ERROR',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  },
} as const

type ValueOf<T> = T[keyof T]

export type ErrorCode
  = | ValueOf<typeof ERROR_CODES.AUTH>
    | ValueOf<typeof ERROR_CODES.USER>
    | ValueOf<typeof ERROR_CODES.BOOK>
    | ValueOf<typeof ERROR_CODES.DICTIONARY>
    | ValueOf<typeof ERROR_CODES.HIGHLIGHT>
    | ValueOf<typeof ERROR_CODES.PLUGIN>
    | ValueOf<typeof ERROR_CODES.LIMITS>
    | ValueOf<typeof ERROR_CODES.QUIZ>
    | ValueOf<typeof ERROR_CODES.TTS>
    | ValueOf<typeof ERROR_CODES.OCR>
    | ValueOf<typeof ERROR_CODES.SYSTEM>
    | string
